### ISSUE TITLE
notusMarkdown.decode: Decoding is not implemented yet

### ISSUE THREAD

**Issue by sil-main-coo** [memspace/zefyr#168]
I tried decode markdown to notus by `notusMarkdown.decode`, 
And the following is the result:
```
Decoding is not implemented yet.

When the exception was thrown, this was the stack: 
#0      NotusMarkdownCodec.decoder (package:notus/src/convert/markdown.dart:15:7)
#1      Codec.decode (dart:convert/codec.dart:26:26)
...
```

### Has this feature been finalized?

**Comment by pulyaevskiy** [comment]
As the error says, it's not implemented yet. But it will, before Zefyr 1.0.

**Comment by nalbion** [comment]
I've created PR #191 for this

**Comment by Jethro87** [comment]
Really looking forward to this feature. It's the one thing holding me back from using Zefyr.
