### ISSUE TITLE
Looking up a deactivated widget's ancestor is unsafe

### ISSUE THREAD

**Issue by Nolence** [memspace/zefyr#341]
## Steps to Reproduce

See [this gist](https://gist.github.com/Nolence/b0569102a23f82cddf9d175dbd265d15) for a minimal example.

I have a quiz app that is composed of a lot of pages inside a `PageView.builder`. Each page has a ZefyrField to edit the question text.

When I navigate from one end of the questions to the other with

```dart
pageController.animateToPage(
  questions.length,
  duration: kDuration,
  curve: kCurve,
),
```

I get this error: 

## Logs

```
[+33702 ms] I/flutter (21446): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY
╞═════════════════════════════════════════════════════════
[   +1 ms] I/flutter (21446): The following assertion was thrown during a scheduler callback:
[        ] I/flutter (21446): Looking up a deactivated widget's ancestor is unsafe.
[        ] I/flutter (21446): At this point the state of the widget's element tree is no longer stable.
[        ] I/flutter (21446): To safely refer to a widget's ancestor in its dispose() method, save a reference to the
ancestor by
[        ] I/flutter (21446): calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
[        ] I/flutter (21446): 
[        ] I/flutter (21446): When the exception was thrown, this was the stack:
[        ] I/flutter (21446): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure>
(package:flutter/src/widgets/framework.dart:3823:9)
[        ] I/flutter (21446): #1      Element._debugCheckStateIsActiveForAncestorLookup
(package:flutter/src/widgets/framework.dart:3837:6)
[        ] I/flutter (21446): #2      Element.dependOnInheritedWidgetOfExactType
(package:flutter/src/widgets/framework.dart:3879:12)
[        ] I/flutter (21446): #3      Scrollable.of (package:flutter/src/widgets/scrollable.dart:253:45)
[        ] I/flutter (21446): #4      _ZefyrLineState.bringIntoView (package:zefyr/src/widgets/common.dart:104:35)
[        ] I/flutter (21446): #5      _ZefyrLineState.ensureVisible.<anonymous closure>
(package:zefyr/src/widgets/common.dart:98:9)
[        ] I/flutter (21446): #6      SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1113:15)
[   +4 ms] I/flutter (21446): #7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1060:9)
[        ] I/flutter (21446): #8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
[        ] I/flutter (21446): #12     _invoke (dart:ui/hooks.dart:267:10)
[        ] I/flutter (21446): #13     _drawFrame (dart:ui/hooks.dart:225:3)
[        ] I/flutter (21446): (elided 3 frames from dart:async)
[        ] I/flutter (21446):
```

```
[✓] Flutter (Channel master, 1.19.0-5.0.pre, on Mac OS X 10.15.5 19F96, locale en-US)
    • Flutter version 1.19.0-5.0.pre at /Users/katzen/flutter
    • Framework revision c2d5e18cb2 (5 days ago), 2020-06-06 10:35:58 -0700
    • Engine revision dbb57f1874
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 249cb9c974)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/katzen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 83.0.4103.97
```

**Comment by HLGB26** [comment]
Hey , i am also facing the same issue , did you find any solution?

See my error also
https://github.com/flutter/flutter/issues/62126#issuecomment-663045010

**Comment by Nolence** [comment]
Yeah, I'm sure this is a Zefyr issue and not a Flutter one. I've also got a simpler example that recreates the issue by using two Zefyr fields in a listview and scrolling out of sight of one.

I can think of a quick fix but it'd involve losing the bring into focus function ZefyrLine uses I think. I'll see if I can find a better fix and do a PR to whichever unofficial branch I'm using and post it here next week

**Comment by HLGB26** [comment]
Yeah , i also think its a Zefyr issue ,occurs when putting Zefyr scaffold in List View . 
Well thanks for reply, and please tell me if you find anything that can solve this problem it would be really helpful.
Again thanks.

**Comment by HLGB26** [comment]
Hey, You said you know a quick fix , can you please describe it would be really helpful.

Also i think that the problem is in the context of comman.dart maybe we can fork the repo and then fix it

**Comment by HLGB26** [comment]
Hey bro i just find a solution use 

Add the AutomaticKeepAliveClientMixin mixin to your State of your StatefulWidget (Item widget), override the wantKeepAlive method and return true.

 class _MarkWidgetState extends State<MarkWidget> with AutomaticKeepAliveClientMixin{
   ...

   @override
   bool get wantKeepAlive => true;
  }
