### ISSUE TITLE
Backspace and cursor issues

### ISSUE THREAD

**Issue by Splashman777** [memspace/zefyr#433]
A few issues I have noticed (all on Android):

- Holding down backspace causes repeated exceptions

- The cursor color does not follow the given theme. It's always blue. It should correspond to the cursorColor theme attribute

- The cursor is always shown even if the ZefyrEditor / ZefyrField is readOnly. This causes confusion for the user and makes them think that they can edit the field when they can't.

## Logs

Errors when holding down backspace.

```

════════ Exception caught by widgets library ═══════════════════════════════════
'package:notus/src/document/node.dart': Failed assertion: line 211 pos 12: 'offset >= 0 && offset <= length': is not true.
The relevant error-causing widget was
MaterialApp
lib\app\main.dart:70
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
No child at position TextPosition(offset: 24, affinity: TextAffinity.downstream)
'package:zefyr/src/rendering/editable_box.dart':
Failed assertion: line 231 pos 12: 'targetChild != null'
The relevant error-causing widget was
MaterialApp
lib\app\main.dart:70
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
No child at position TextPosition(offset: 23, affinity: TextAffinity.downstream)
'package:zefyr/src/rendering/editable_box.dart':
Failed assertion: line 231 pos 12: 'targetChild != null'
The relevant error-causing widget was
MaterialApp
lib\app\main.dart:70
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:notus/src/document/node.dart': Failed assertion: line 211 pos 12: 'offset >= 0 && offset <= length': is not true.
The relevant error-causing widget was
MaterialApp
lib\app\main.dart:70
════════════════════════════════════════════════════════════════════════════════


```

```
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.22.3 at C:\Users\jared\Flutter\flutter
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2) 
    • Android SDK at C:\Users\jared\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.0)
    • VS Code at C:\Users\jared\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • ONEPLUS A6003 (mobile) • f79d8aac • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by pulyaevskiy** [comment]
I think the backspace issue should be mostly addressed in the latest 1.0.0-rc release. Need to check the styling piece.

**Comment by britannio** [comment]
@pulyaevskiy The exception still occurs in v 1.0.0-rc.4
```
I/flutter ( 5435): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5435): The following assertion was thrown building _TextSelectionHandleOverlay(dirty, dependencies:
I/flutter ( 5435): [_InheritedTheme, _EffectiveTickerMode, _LocalizationsScope-[GlobalKey#0a378]], state:
I/flutter ( 5435): _TextSelectionHandleOverlayState#3c22e(ticker active)):
I/flutter ( 5435): 'package:notus/src/document/node.dart': Failed assertion: line 209 pos 12: 'offset >= 0 && offset <=
package:notus/…/document/node.dart:1
I/flutter ( 5435): length': is not true.
I/flutter ( 5435):
I/flutter ( 5435): The relevant error-causing widget was:
I/flutter ( 5435):   Visibility
I/flutter ( 5435):
lib/…/src/state_preserving_switcher.dart:26
I/flutter ( 5435):
I/flutter ( 5435): When the exception was thrown, this was the stack:
I/flutter ( 5435): #2      ContainerNode.lookup
package:notus/…/document/node.dart:209
I/flutter ( 5435): #3      RenderEditableContainerBox.childAtPosition
package:zefyr/…/rendering/editable_box.dart:234
I/flutter ( 5435): #4      RenderEditor.preferredLineHeight
package:zefyr/…/rendering/editor.dart:728
I/flutter ( 5435): #5      _TextSelectionHandleOverlayState.build
package:zefyr/…/widgets/text_selection.dart:544
I/flutter ( 5435): #6      StatefulElement.build
package:flutter/…/widgets/framework.dart:4705
I/flutter ( 5435): #7      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4588
I/flutter ( 5435): #8      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4763
I/flutter ( 5435): #9      Element.rebuild
package:flutter/…/widgets/framework.dart:4311
I/flutter ( 5435): #10     StatefulElement.update
package:flutter/…/widgets/framework.dart:4795
I/flutter ( 5435): #11     Element.updateChild
package:flutter/…/widgets/framework.dart:3370
I/flutter ( 5435): #12     ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4613
I/flutter ( 5435): #13     Element.rebuild
package:flutter/…/widgets/framework.dart:4311
I/flutter ( 5435): #14     StatelessElement.update
package:flutter/…/widgets/framework.dart:4669
I/flutter ( 5435): #15     Element.updateChild
package:flutter/…/widgets/framework.dart:3370
I/flutter ( 5435): #16     ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4613
I/flutter ( 5435): #17     Element.rebuild
package:flutter/…/widgets/framework.dart:4311
I/flutter ( 5435): #18     ProxyElement.update
package:flutter/…/widgets/framework.dart:4943
I/flutter ( 5435): #19     Element.updateChild
package:flutter/…/widgets/framework.dart:3370
I/flutter ( 5435): #20     ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4613
I/flutter ( 5435): #21     Element.rebuild
package:flutter/…/widgets/framework.dart:4311
I/flutter ( 5435): #22     StatelessElement.update
package:flutter/…/widgets/framework.dart:4669
I/flutter ( 5435): #23     Element.updateChild
package:flutter/…/widgets/framework.dart:3370
I/flutter ( 5435): #24     ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4613
I/flutter ( 5435): #25     StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4763
I/flutter ( 5435): #26     Element.rebuild
package:flutter/…/widgets/framework.dart:4311
I/flutter ( 5435): #27     BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2578
I/flutter ( 5435): #28     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:882
I/flutter ( 5435): #29     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:363
I/flutter ( 5435): #30     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1145
I/flutter ( 5435): #31     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1082
I/flutter ( 5435): #32     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:996
I/flutter ( 5435): #36     _invoke (dart:ui/hooks.dart:150:10)
I/flutter ( 5435): #37     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
I/flutter ( 5435): #38     _drawFrame (dart:ui/hooks.dart:114:31)
I/flutter ( 5435): (elided 5 frames from class _AssertionError and dart:async)
I/flutter ( 5435):
I/flutter ( 5435): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
