### ISSUE TITLE
How to add newline or space after attach a image?

### ISSUE THREAD

**Issue by sorrychan** [memspace/zefyr#469]
Hi, I have trouble with attaching an image.
I tried to put image between two images without any character, the exception occurs.

When add any character like space or newline after that image, this issue not occurs.
So I think put some character after attach an image can prevent issue.

I'm using zefyr 0.12.0.

- Steps to reproduce.

1. Attach two images from gallery in a row. (no character between two images)
2. Set editor cursor to first Image. 
3. Try to attach image and the exception occurs.

- Logs

E/flutter ( 2162): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FileSystemException: Cannot open file, path = '/data/user/0/com.tmr.google/cache/file_picker/2.gif' (OS Error: No such file or directory, errno = 2)
E/flutter ( 2162): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
E/flutter ( 2162): #1      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 2162): #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 2162): #3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 2162): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 2162): #5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 2162): #6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 2162): #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter ( 2162): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 2162): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 2162): #10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 2162): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 2162): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 2162): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

-flutter doctor -v
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18363.1256], locale ko-KR)
    • Flutter version 1.22.2 at C:\src\flutter
    • Framework revision 84f3d28555 (3 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\csk\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\csk\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

**Comment by singerdmx** [comment]
Here is how I implemented it

https://github.com/singerdmx/flutter-quill/commit/bb6fd50f36d9b25508d045c4e6cbfd2656c205a3#diff-d87ca9ebf40459cf9411294e8f1775bcc0e69731b30d7b95f490a5b80dcabc83

https://github.com/singerdmx/flutter-quill/commit/1d900afa70ac0c5b188978c7b7ced9a478616358#diff-d87ca9ebf40459cf9411294e8f1775bcc0e69731b30d7b95f490a5b80dcabc83

**Comment by singerdmx** [comment]
Or you can just use this method

https://github.com/singerdmx/flutter-quill/blob/master/lib/models/documents/document.dart#L181

**Comment by sorrychan** [comment]
@singerdmx  Thank you for your help. But I want to implement this method with zefyr editor and can't find proper insert position.
