### ISSUE TITLE
ZefyrField: error when bold and italic to toggle on

### ISSUE THREAD

**Issue by KolesnikovaKristinavm** [memspace/zefyr#504]
I got an error when bold and italic to toggle on.

## Steps to Reproduce

1. Set bold or italic to toggle on
2. Try to go to a new line

## Logs
I/flutter ( 6118): ══╡ EXCEPTION CAUGHT BY ZEFYR ╞═════════════════════════════════════════════════════════════════════
I/flutter ( 6118): The following assertion was thrown while updating editing value:
I/flutter ( 6118): It is not allowed to apply inline attributes to line itself.
I/flutter ( 6118): 'package:notus/src/document/line.dart':
I/flutter ( 6118): Failed assertion: line 231 pos 11: 'style.values.every((attr) => attr.scope ==
I/flutter ( 6118): NotusAttributeScope.line)'
I/flutter ( 6118):
I/flutter ( 6118): When the exception was thrown, this was the stack:
I/flutter ( 6118): #2      LineNode.retain
package:notus/…/document/line.dart:231
I/flutter ( 6118): #3      ContainerNode.retain
package:notus/…/document/node.dart:254
I/flutter ( 6118): #4      NotusDocument.compose
package:notus/src/document.dart:235
I/flutter ( 6118): #5      ZefyrController.replaceText
package:zefyr/…/widgets/controller.dart:133
I/flutter ( 6118): #6      _ZefyrEditableTextState._handleRemoteValueChange
package:zefyr/…/widgets/editable_text.dart:319
I/flutter ( 6118): #7      InputConnectionController.updateEditingValue
package:zefyr/…/widgets/input.dart:152
I/flutter ( 6118): #8      TextInput._handleTextInputInvocation
package:flutter/…/services/text_input.dart:1165
I/flutter ( 6118): #9      MethodChannel._handleAsMethodCall
package:flutter/…/services/platform_channel.dart:430
I/flutter ( 6118): #10     MethodChannel.setMethodCallHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:383
I/flutter ( 6118): #11     _DefaultBinaryMessenger.handlePlatformMessage
package:flutter/…/services/binding.dart:283
I/flutter ( 6118): #12     _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
I/flutter ( 6118): #16     _invoke3 (dart:ui/hooks.dart:279:10)
I/flutter ( 6118): #17     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5)
I/flutter ( 6118): (elided 5 frames from class _AssertionError and dart:async)
I/flutter ( 6118): ════════════════════════════════════════════════════════════════════════════════════════════════════

```
```

**Comment by singerdmx** [comment]
This repo has been inactive for months.  See https://github.com/memspace/zefyr/issues/409#issuecomment-790671992

Just FYI to save your time here.
