### ISSUE TITLE
Can't remove last character of text

### ISSUE THREAD

**Issue by Amir-P** [memspace/zefyr#553]
## Steps to Reproduce

1. Use Zefyr on a real device (iOS or Android)
2. Type a text
3. Try removing text by characters
4. The last character won't get removed on iOS on first try and instead it get's selected and you have to put cursor to in front of it and remove it again. On Android the same thing happens but with a difference: After a failed attempt to remove the character, If you try to remove the character again, Notus document will be messed up and you have to create another one!

I believe this issue is again related to `_sentRemoteValues` and the logic inside `updateEditingValue` of `RawEditorStateTextInputClientMixin`.

https://user-images.githubusercontent.com/8766492/141612799-a5ad749e-0a6e-4a9b-b5e8-5efc7b674f39.mp4

https://user-images.githubusercontent.com/8766492/141612805-fd86ab66-69ba-4d69-9d88-a81ad32117fa.mov

## Logs

This log is from running application on Android and after removing the last character:
```
══╡ EXCEPTION CAUGHT BY ZEFYR
╞═════════════════════════════════════════════════════════════════════
The following assertion was thrown while updating editing value:
'package:notus/src/document/node.dart': Failed assertion: line 235 pos 12:
'index == 0 || (index > 0
&& index < length)': is not true.

When the exception was thrown, this was the stack:
#2      ContainerNode.insert (package:notus/src/document/node.dart:235:12)
#3      NotusDocument.compose (package:notus/src/document.dart:241:15)
#4      NotusDocument.insert (package:notus/src/document.dart:117:5)
#5      NotusDocument.replace (package:notus/src/document.dart:157:15)
#6      ZefyrController.replaceText
(package:zefyr/src/widgets/controller.dart:67:24)
#7      RawEditorStateTextInputClientMixin._remoteValueChanged
(package:zefyr/src/widgets/editor_input_client_mixin.dart:33:10)
#8      RawEditorStateTextInputClientMixin.updateEditingValue
(package:zefyr/src/widgets/editor_input_client_mixin.dart:182:7)
#9      TextInput._handleTextInputInvocation
(package:flutter/src/services/text_input.dart:1386:37)
#10     MethodChannel._handleAsMethodCall
(package:flutter/src/services/platform_channel.dart:386:55)
#11     MethodChannel.setMethodCallHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:379:34)
#12     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
(package:flutter/src/services/binding.dart:379:35)
#13     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
(package:flutter/src/services/binding.dart:376:46)
#14     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
#18     _invoke2 (dart:ui/hooks.dart:204:10)
#19     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#20     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#21     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#22     PlatformDispatcher._dispatchPlatformMessage
(dart:ui/platform_dispatcher.dart:544:22)
#23     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════
════════════════════
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
[✓] VS Code (version 1.62.1)
[✓] Connected device (2 available)
```

**Comment by pulyaevskiy** [comment]
@Amir-P could you please verify if this is now resolved and close?

**Comment by Amir-P** [comment]
It's fixed now. @pulyaevskiy
