### ISSUE TITLE
open camera need request permission first

### ISSUE THREAD

**Issue by linguitang** [memspace/zefyr#94]
```
E/MethodChannel#plugins.flutter.io/image_picker( 9541): Failed to handle method call
E/MethodChannel#plugins.flutter.io/image_picker( 9541): java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera/.Camera clip={text/uri-list U:content://com.XX.flutter.image_provider/external_files/Android/data/com.XX/files/Pictures/ee70561a-1a8a-4273-b464-c9029c3bffc6-373123557.jpg} (has extras) } from ProcessRecord{a1051f7 9541:com.mld.cc/u0a198} (pid=9541, uid=10198) with revoked permission android.permission.CAMERA
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at android.os.Parcel.readException(Parcel.java:1620)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at android.os.Parcel.readException(Parcel.java:1573)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2837)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1509)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at android.app.Activity.startActivityForResult(Activity.java:4032)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at android.app.Activity.startActivityForResult(Activity.java:3993)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.launchTakeImageWithCameraIntent(ImagePickerDelegate.java:282)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.takeImageWithCamera(ImagePickerDelegate.java:263)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.onMethodCall(ImagePickerPlugin.java:64)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at android.os.Looper.loop(Looper.java:141)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at android.app.ActivityThread.main(ActivityThread.java:5696)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
E/MethodChannel#plugins.flutter.io/image_picker( 9541): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
D/AndroidRuntime( 9541): Shutting down VM
E/AndroidRuntime( 9541): FATAL EXCEPTION: main
```

**Comment by pulyaevskiy** [comment]
Closing this as zefyr no longer depends on image_picker and user's will need to follow instructions of whichever plugin they choose to use for embedding images.
